version: "3.8"

services:
  online_shop:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: online_shop
    ports:
      - "8080:80"  # Map your computer's 8080 to Nginx's 80
    restart: always
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost/health"]
      interval: 30s
      timeout: 5s
      retries: 3
    networks:
      - online_shop_net

networks:
  online_shop_net:
    driver: bridge