apiVersion: v1
kind: Service
metadata:
  name: online-shop-service
  namespace: online-shop
spec:
  selector:
    app: online-shop
  ports:
    - protocol: TCP
      port: 5173
      targetPort: 80
      
