apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: online-shop-vpa
  namespace: online-shop
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: online-shop-deployment
  updatePolicy:
    updateMode: Auto
